export const portfolioData = {
    name: "Arthikan Vettivel",
    title: "UI/UX Engineer • Software Engineer",
    intro: "I design elegant experiences and engineer powerful software that scale.",
    stats: [
        { label: "Projects Built", value: "20+" },
        { label: "Technologies", value: "15+" },
        { label: "Happy Clients", value: "12+" },
    ],
    navLinks: [
        { name: "Home", href: "#home" },
        { name: "About", href: "#about" },
        { name: "Skills", href: "#skills" },
        { name: "Projects", href: "#projects" },
        { name: "Services", href: "#services" },
        { name: "Contact", href: "#contact" },
    ],
    skills: [
        { name: "Figma", category: "Design", icon: "SiFigma" },
        { name: "Photoshop", category: "Design", icon: "SiAdobephotoshop" },
        { name: "Adobe Illustrator", category: "Design", icon: "SiAdobeillustrator" },
        { name: "After Effects", category: "Design", icon: "SiAdobeaftereffects" },
        { name: "Canva", category: "Design", icon: "SiCanva" },
        { name: "HTML5", category: "Frontend", icon: "SiHtml5" },
        { name: "CSS3", category: "Frontend", icon: "SiCss3" },
        { name: "JavaScript", category: "Frontend", icon: "SiJavascript" },
        { name: "TypeScript", category: "Frontend", icon: "SiTypescript" },
        { name: "React", category: "Frontend", icon: "SiReact" },
        { name: "Next.js", category: "Frontend", icon: "SiNextdotjs" },
        { name: "Tailwind CSS", category: "Frontend", icon: "SiTailwindcss" },
        { name: "Three.js", category: "Frontend", icon: "SiThreedotjs" },
        { name: "Framer Motion", category: "Frontend", icon: "SiFramer" },
        { name: "WordPress", category: "CMS", icon: "SiWordpress" },
        { name: "Shopify", category: "CMS", icon: "SiShopify" },
        { name: "Webflow", category: "CMS", icon: "SiWebflow" },
        { name: "Node.js", category: "Backend", icon: "SiNodedotjs" },
        { name: "Python", category: "Backend", icon: "SiPython" },
        { name: "Firebase", category: "Backend", icon: "SiFirebase" },
        { name: "Digital Marketing", category: "Growth", icon: "SiGoogleads" },
        { name: "SEO", category: "Growth", icon: "SiGoogle" },
        { name: "Google Analytics", category: "Growth", icon: "SiGoogleanalytics" },
        { name: "Git", category: "Tools", icon: "SiGit" },
        { name: "VS Code", category: "Tools", icon: "SiVisualstudiocode" },
        { name: "Vercel", category: "Tools", icon: "SiVercel" },
    ],
    projects: [
        {
            title: "Project Alpha",
            description: "A high-performance dashboard for financial analytics with real-time data visualization.",
            tech: ["Next.js", "Three.js", "Tailwind"],
            link: "#",
            image: "/projects/alpha.png",
        },
        {
            title: "Project Beta",
            description: "Next-gen e-commerce experience with interactive 3D product previews.",
            tech: ["React", "Framer Motion", "Three.js"],
            link: "#",
            image: "/projects/beta.png",
        },
    ],
    services: [
        {
            title: "UI/UX Design",
            description: "Creating intuitive and beautiful interfaces that users love.",
            icon: "Palette",
        },
        {
            title: "Web Development",
            description: "Building fast, responsive, and scalable web applications.",
            icon: "Code",
        },
        {
            title: "Full Stack Systems",
            description: "End-to-end solutions with robust backend and seamless frontend.",
            icon: "Layers",
        },
    ],
    education: [
        {
            degree: "G.C.E. Ordinary Level & Advanced Level",
            institution: "J/ Nelliady Central College",
            period: "2011 - 2019",
            description: "Built a strong academic foundation with a focus on Mathematics and Science. Developed early passion for technology and problem-solving.",
        },
        {
            degree: "HND in Software Engineering",
            institution: "Esoft Metro Campus",
            period: "2024 - 2025",
            description: "Completed Higher National Diploma with a focus on full-stack development, database management, and software project lifecycle.",
        },
        {
            degree: "BSc in Software Engineering",
            institution: "Esoft Metro Campus",
            period: "2026 - 2027 (Currently)",
            description: "Pursuing a Bachelor's degree in Software Engineering, deepening expertise in advanced programming, system design, and emerging technologies.",
        },

    ],
    contact: {
        email: "arthikandev@gmail.com",
        socials: [
            { name: "LinkedIn", url: "https://www.linkedin.com/in/arthikan-vettivel-77a5b92b2/", icon: "Linkedin" },
            { name: "GitHub", url: "#", icon: "Github" },
            { name: "Twitter", url: "#", icon: "Twitter" },
        ],
    },
};
